import { createContext, useContext, useState, useCallback } from 'react';
import type { ReactNode } from 'react';
import type { Lang } from './types';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'app.title': 'Samadhan',
    'app.subtitle': 'Public Grievance Platform',
    'lang.select': 'Select Language',
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी',
    'home.speak': 'Speak your complaint',
    'home.or': 'OR',
    'home.categories': 'Select a category',
    'home.track': 'Track My Complaint',
    'home.myComplaints': 'My Complaints',
    'register.title': 'Register Complaint',
    'register.step.category': 'Category',
    'register.step.subtype': 'Sub-type',
    'register.step.location': 'Location',
    'register.step.description': 'Details',
    'register.step.contact': 'Your Details',
    'register.step.review': 'Review & Submit',
    'register.selectCategory': 'Select Category',
    'register.selectSubType': 'What is the issue?',
    'register.locationLabel': 'Where is the problem?',
    'register.locationPlaceholder': 'Enter address or landmark',
    'register.useMyLocation': 'Use my location',
    'register.descriptionLabel': 'Describe the problem',
    'register.descriptionPlaceholder': 'Tell us more about the issue...',
    'register.photoLabel': 'Add Photo',
    'register.takePhoto': 'Take Photo',
    'register.phoneLabel': 'Phone Number',
    'register.phonePlaceholder': 'Enter 10-digit mobile number',
    'register.nameLabel': 'Your Name',
    'register.namePlaceholder': 'Enter your name',
    'register.reviewTitle': 'Review Your Complaint',
    'register.submit': 'Submit Complaint',
    'register.success.title': 'Complaint Registered!',
    'register.success.message': 'Your complaint has been registered successfully.',
    'register.success.caseNumber': 'Case Number',
    'register.success.goHome': 'Go to Home',
    'register.success.track': 'Track Complaint',
    'register.next': 'Next',
    'register.back': 'Back',
    'register.category': 'Category',
    'register.subType': 'Issue Type',
    'register.location': 'Location',
    'register.description': 'Description',
    'register.phone': 'Phone',
    'register.name': 'Name',
    'track.title': 'Track Complaints',
    'track.phoneLabel': 'Enter your phone number',
    'track.phonePlaceholder': 'Enter 10-digit mobile number',
    'track.search': 'Search',
    'track.myComplaints': 'My Complaints',
    'track.noComplaints': 'No complaints found.',
    'detail.title': 'Complaint Details',
    'detail.caseNumber': 'Case Number',
    'detail.category': 'Category',
    'detail.location': 'Location',
    'detail.date': 'Date Filed',
    'detail.description': 'Description',
    'detail.officer': 'Assigned Officer',
    'detail.timeline': 'Timeline',
    'detail.giveFeedback': 'Give Feedback',
    'detail.status': 'Status',
    'progress.received': 'Received',
    'progress.assigned': 'Assigned',
    'progress.workDone': 'Work Done',
    'progress.closed': 'Closed',
    'feedback.title': 'Feedback',
    'feedback.question': 'Was your complaint resolved satisfactorily?',
    'feedback.yes': 'Yes, Satisfied',
    'feedback.no': 'No, Not Satisfied',
    'feedback.commentLabel': 'Additional comments (optional)',
    'feedback.commentPlaceholder': 'Tell us more...',
    'feedback.thanks': 'Thank you for your feedback!',
    'feedback.goHome': 'Go to Home',
    'status.RECEIVED': 'Received',
    'status.ASSIGNED': 'Assigned',
    'status.IN_PROGRESS': 'In Progress',
    'status.RESOLVED': 'Resolved',
    'status.CLOSED': 'Closed',
    'status.REOPENED': 'Reopened',
  },
  hi: {
    'app.title': 'समाधान',
    'app.subtitle': 'लोक शिकायत मंच',
    'lang.select': 'भाषा चुनें',
    'lang.english': 'English',
    'lang.hindi': 'हिन्दी',
    'home.speak': 'अपनी शिकायत बोलें',
    'home.or': 'या',
    'home.categories': 'श्रेणी चुनें',
    'home.track': 'शिकायत ट्रैक करें',
    'home.myComplaints': 'मेरी शिकायतें',
    'register.title': 'शिकायत दर्ज करें',
    'register.step.category': 'श्रेणी',
    'register.step.subtype': 'उप-प्रकार',
    'register.step.location': 'स्थान',
    'register.step.description': 'विवरण',
    'register.step.contact': 'आपकी जानकारी',
    'register.step.review': 'समीक्षा और जमा',
    'register.selectCategory': 'श्रेणी चुनें',
    'register.selectSubType': 'समस्या क्या है?',
    'register.locationLabel': 'समस्या कहाँ है?',
    'register.locationPlaceholder': 'पता या लैंडमार्क दर्ज करें',
    'register.useMyLocation': 'मेरी लोकेशन का उपयोग करें',
    'register.descriptionLabel': 'समस्या का विवरण',
    'register.descriptionPlaceholder': 'समस्या के बारे में बताएं...',
    'register.photoLabel': 'फोटो जोड़ें',
    'register.takePhoto': 'फोटो लें',
    'register.phoneLabel': 'फोन नंबर',
    'register.phonePlaceholder': '10 अंकों का मोबाइल नंबर',
    'register.nameLabel': 'आपका नाम',
    'register.namePlaceholder': 'अपना नाम दर्ज करें',
    'register.reviewTitle': 'अपनी शिकायत की समीक्षा',
    'register.submit': 'शिकायत जमा करें',
    'register.success.title': 'शिकायत दर्ज!',
    'register.success.message': 'आपकी शिकायत सफलतापूर्वक दर्ज हो गई है।',
    'register.success.caseNumber': 'केस नंबर',
    'register.success.goHome': 'होम पेज',
    'register.success.track': 'शिकायत ट्रैक करें',
    'register.next': 'आगे',
    'register.back': 'पीछे',
    'register.category': 'श्रेणी',
    'register.subType': 'समस्या प्रकार',
    'register.location': 'स्थान',
    'register.description': 'विवरण',
    'register.phone': 'फोन',
    'register.name': 'नाम',
    'track.title': 'शिकायत ट्रैक करें',
    'track.phoneLabel': 'अपना फोन नंबर दर्ज करें',
    'track.phonePlaceholder': '10 अंकों का मोबाइल नंबर',
    'track.search': 'खोजें',
    'track.myComplaints': 'मेरी शिकायतें',
    'track.noComplaints': 'कोई शिकायत नहीं मिली।',
    'detail.title': 'शिकायत विवरण',
    'detail.caseNumber': 'केस नंबर',
    'detail.category': 'श्रेणी',
    'detail.location': 'स्थान',
    'detail.date': 'दर्ज तिथि',
    'detail.description': 'विवरण',
    'detail.officer': 'नियुक्त अधिकारी',
    'detail.timeline': 'समयरेखा',
    'detail.giveFeedback': 'प्रतिक्रिया दें',
    'detail.status': 'स्थिति',
    'progress.received': 'प्राप्त',
    'progress.assigned': 'सौंपा',
    'progress.workDone': 'कार्य पूर्ण',
    'progress.closed': 'बंद',
    'feedback.title': 'प्रतिक्रिया',
    'feedback.question': 'क्या आपकी शिकायत संतोषजनक रूप से हल हुई?',
    'feedback.yes': 'हाँ, संतुष्ट',
    'feedback.no': 'नहीं, असंतुष्ट',
    'feedback.commentLabel': 'अतिरिक्त टिप्पणी (वैकल्पिक)',
    'feedback.commentPlaceholder': 'और बताएं...',
    'feedback.thanks': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    'feedback.goHome': 'होम पेज',
    'status.RECEIVED': 'प्राप्त',
    'status.ASSIGNED': 'सौंपा गया',
    'status.IN_PROGRESS': 'प्रगति पर',
    'status.RESOLVED': 'समाधान',
    'status.CLOSED': 'बंद',
    'status.REOPENED': 'पुनः खोला',
  },
};

interface LangContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Lang>('en');

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] ?? key;
    },
    [language]
  );

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
