import { createContext, useContext, useState, useCallback } from 'react';
import type { ReactNode } from 'react';
import type { Lang } from './types';

const translations: Record<Lang, Record<string, string>> = {
  hi: {
    'app.title': 'समाधान',
    'app.subtitle': 'लोक शिकायत मंच',
    'lang.select': 'अपनी भाषा चुनें',
    'lang.selectSub': 'Select your language',
    'lang.consent': 'आगे बढ़कर आप सहमति देते हैं कि आपकी आवाज़ और फ़ोटो केवल शिकायत के लिए उपयोग होगी। आधार नहीं माँगा जाएगा।',
    'lang.consentEn': 'By proceeding you consent to use of your voice and photos only for the complaint. Aadhaar is never collected.',
    'lang.continue': 'आगे बढ़ें · Continue',
    'home.voice': 'बोलकर शिकायत करें',
    'home.voiceSub': 'Speak your complaint',
    'home.pick': 'तस्वीर देखकर चुनें',
    'home.pickSub': 'Pick from pictures',
    'home.seeAll': 'सभी देखें',
    'home.seeAllSub': 'See all',
    'home.track': 'मेरी शिकायतें',
    'home.trackSub': 'My complaints',
    'home.speak': 'बोलें',
    'home.speakSub': 'Speak',
    'home.homeSub': 'Home',
    'cat.title': 'क्या समस्या है?',
    'cat.titleSub': 'What is the problem?',
    'cat.other': 'कुछ और',
    'cat.otherSub': 'Something else — speak',
    'sub.title': 'कौन सी समस्या?',
    'sub.titleSub': 'What exactly?',
    'sub.other': 'कुछ और',
    'sub.otherSub': 'Other — describe',
    'sub.slaLabel': 'में काम होगा · within',
    'loc.title': 'क्या यह सही जगह है?',
    'loc.titleSub': 'Is this the right location?',
    'loc.yes': 'हाँ, सही है',
    'loc.yesSub': 'Yes, correct',
    'loc.change': 'जगह बदलें',
    'loc.changeSub': 'Change location',
    'loc.detecting': 'जगह पता कर रहे हैं…',
    'loc.detectingSub': 'Detecting location…',
    'loc.gps': 'GPS से जगह लें',
    'loc.gpsSub': 'Use GPS location',
    'media.title': 'फ़ोटो या वीडियो लें',
    'media.titleSub': 'Take photo or video',
    'media.photo': 'फ़ोटो लें',
    'media.photoSub': 'Take photo',
    'media.video': 'वीडियो लें',
    'media.videoSub': 'Record video',
    'media.skip': 'बिना फ़ोटो आगे',
    'media.skipSub': 'Skip, no photo',
    'media.added': 'जोड़ दिया गया',
    'media.addedSub': 'Added',
    'media.retake': 'दोबारा लें',
    'media.retakeSub': 'Retake',
    'review.title': 'एक बार सुन लें',
    'review.titleSub': 'Check once before sending',
    'review.listen': 'पूरा सुनें · Listen to all',
    'review.send': 'शिकायत भेजें · Send',
    'review.photo': 'फ़ोटो लगी है',
    'review.photoSub': 'photo added',
    'review.video': 'वीडियो लगा है',
    'review.videoSub': 'video added',
    'review.noMedia': 'फ़ोटो नहीं · No photo',
    'success.title': 'शिकायत दर्ज हो गई!',
    'success.titleSub': 'Your complaint is registered',
    'success.number': 'आपका नंबर · YOUR NUMBER',
    'success.hear': 'नंबर सुनें · Hear number',
    'success.whatsapp': 'WhatsApp पर भी भेजा गया · Sent on WhatsApp',
    'success.addPhoto': 'फ़ोटो भेजें · Add a photo',
    'success.home': 'होम',
    'success.myComplaints': 'मेरी शिकायतें',
    'track.title': 'मेरी शिकायतें',
    'track.titleSub': 'My complaints',
    'track.earlier': 'पुरानी शिकायतें',
    'track.earlierSub': 'Earlier',
    'track.status': 'स्थिति सुनें · Hear status',
    'detail.listen': 'सुनें',
    'detail.worker': 'कर्मचारी',
    'detail.workerSub': 'Assigned worker',
    'detail.atrPhoto': 'काम के बाद की फ़ोटो · After-work photo',
    'feedback.title': 'क्या काम ठीक हुआ?',
    'feedback.titleSub': 'Is the problem fixed?',
    'feedback.yes': 'हाँ · Yes',
    'feedback.no': 'नहीं · No',
    'feedback.voice': 'बोलकर बताएँ (ज़रूरी नहीं) · Add voice comment',
    'feedback.thanks': 'धन्यवाद! शिकायत बंद हुई।',
    'feedback.thanksSub': 'Thank you! Complaint closed.',
    'feedback.reopened': 'शिकायत फिर से खोली गई',
    'feedback.reopenedSub': 'Reopened and sent back. We will update you.',
    'voice.title': 'बोलकर शिकायत करें',
    'voice.titleSub': 'Speak your complaint',
    'voice.instruction': 'लाल बटन दबाएँ और बोलना शुरू करें',
    'voice.instructionSub': 'Press the red button and start speaking',
    'voice.tapToRecord': 'बटन दबाएँ · Tap to record',
    'voice.recording': 'सुन रहे हैं… · Recording…',
    'voice.recorded': 'रिकॉर्ड हो गया · Recorded',
    'voice.rerecord': 'दोबारा बोलें · Re-record',
    'voice.next': 'आगे · Next',
    'loc.detected': 'पकड़ा गया',
    'loc.orSelect': 'या नीचे से जगह चुनें · Or select from below',
    'loc.error': 'GPS नहीं मिला',
    'loc.errorSub': 'Location access denied or unavailable',
    'loc.retry': 'फिर से',
    'other.placeholder': 'अपनी समस्या यहाँ लिखें…',
    'other.placeholderEn': 'Describe your problem here…',
    'login.title': 'लॉगिन करें',
    'login.titleSub': 'Login to continue',
    'login.name': 'आपका नाम · Your name',
    'login.namePlaceholder': 'अपना नाम लिखें',
    'login.phone': 'मोबाइल नंबर · Mobile number',
    'login.sendOtp': 'OTP भेजें · Send OTP',
    'login.otp': 'OTP डालें · Enter OTP',
    'login.otpSent': 'OTP भेजा गया · OTP sent to',
    'login.verify': 'पुष्टि करें · Verify',
    'login.changePhone': 'नंबर बदलें · Change number',
    'login.phoneError': 'कृपया 10 अंक का नंबर डालें',
    'login.nameError': 'कृपया अपना नाम डालें',
    'login.otpError': 'गलत OTP · Demo OTP: 1234',
    'login.demo': 'डेमो: किसी भी 10 अंक के नंबर और OTP 1234 से लॉगिन करें · Demo: Use any 10-digit number and OTP 1234',
    'login.logout': 'लॉगआउट · Logout',
    'voice.transcribing': 'समझ रहे हैं… · Transcribing…',
    'voice.transcript': 'आपने कहा · You said',
    'voice.detected': 'विभाग पहचाना · Department detected',
    'map.title': 'नक्शे पर जगह चुनें',
    'map.titleSub': 'Choose on map',
    'map.search': 'जगह खोजें',
    'map.select': 'यह जगह चुनें',
    'track.noComplaints': 'अभी कोई शिकायत नहीं है',
    'track.noComplaintsSub': 'No complaints yet. File one from home.',
    'track.fileNew': 'नई शिकायत करें · File new complaint',
  },
  en: {
    'app.title': 'Samadhan',
    'app.subtitle': 'Public Grievance Platform',
    'lang.select': 'Select your language',
    'lang.selectSub': 'अपनी भाषा चुनें',
    'lang.consent': 'By proceeding you consent to use of your voice and photos only for the complaint. Aadhaar is never collected.',
    'lang.consentEn': '',
    'lang.continue': 'Continue · आगे बढ़ें',
    'home.voice': 'Speak your complaint',
    'home.voiceSub': 'बोलकर शिकायत करें',
    'home.pick': 'Pick from pictures',
    'home.pickSub': 'तस्वीर देखकर चुनें',
    'home.seeAll': 'See all',
    'home.seeAllSub': 'सभी देखें',
    'home.track': 'My complaints',
    'home.trackSub': 'मेरी शिकायतें',
    'home.speak': 'Speak',
    'home.speakSub': 'बोलें',
    'home.homeSub': 'होम',
    'cat.title': 'What is the problem?',
    'cat.titleSub': 'क्या समस्या है?',
    'cat.other': 'Something else',
    'cat.otherSub': 'Speak your problem',
    'sub.title': 'What exactly?',
    'sub.titleSub': 'कौन सी समस्या?',
    'sub.other': 'Other',
    'sub.otherSub': 'Describe the problem',
    'sub.slaLabel': 'within',
    'loc.title': 'Is this the right location?',
    'loc.titleSub': 'क्या यह सही जगह है?',
    'loc.yes': 'Yes, correct',
    'loc.yesSub': 'हाँ, सही है',
    'loc.change': 'Change location',
    'loc.changeSub': 'जगह बदलें',
    'loc.detecting': 'Detecting location…',
    'loc.detectingSub': 'जगह पता कर रहे हैं…',
    'loc.gps': 'Use GPS location',
    'loc.gpsSub': 'GPS से जगह लें',
    'media.title': 'Take photo or video',
    'media.titleSub': 'फ़ोटो या वीडियो लें',
    'media.photo': 'Take photo',
    'media.photoSub': 'फ़ोटो लें',
    'media.video': 'Record video',
    'media.videoSub': 'वीडियो लें',
    'media.skip': 'Skip, no photo',
    'media.skipSub': 'बिना फ़ोटो आगे',
    'media.added': 'Added',
    'media.addedSub': 'जोड़ दिया गया',
    'media.retake': 'Retake',
    'media.retakeSub': 'दोबारा लें',
    'review.title': 'Review before sending',
    'review.titleSub': 'एक बार सुन लें',
    'review.listen': 'Listen to all · पूरा सुनें',
    'review.send': 'Send complaint · शिकायत भेजें',
    'review.photo': 'photo added',
    'review.photoSub': 'फ़ोटो लगी है',
    'review.video': 'video added',
    'review.videoSub': 'वीडियो लगा है',
    'review.noMedia': 'No photo · फ़ोटो नहीं',
    'success.title': 'Complaint registered!',
    'success.titleSub': 'शिकायत दर्ज हो गई',
    'success.number': 'YOUR NUMBER · आपका नंबर',
    'success.hear': 'Hear number · नंबर सुनें',
    'success.whatsapp': 'Sent on WhatsApp · WhatsApp पर भेजा',
    'success.addPhoto': 'Add a photo · फ़ोटो भेजें',
    'success.home': 'Home',
    'success.myComplaints': 'My complaints',
    'track.title': 'My complaints',
    'track.titleSub': 'मेरी शिकायतें',
    'track.earlier': 'Earlier',
    'track.earlierSub': 'पुरानी शिकायतें',
    'track.status': 'Hear status · स्थिति सुनें',
    'detail.listen': 'Listen',
    'detail.worker': 'Assigned worker',
    'detail.workerSub': 'कर्मचारी',
    'detail.atrPhoto': 'After-work photo · काम के बाद की फ़ोटो',
    'feedback.title': 'Is the problem fixed?',
    'feedback.titleSub': 'क्या काम ठीक हुआ?',
    'feedback.yes': 'Yes · हाँ',
    'feedback.no': 'No · नहीं',
    'feedback.voice': 'Add voice comment (optional)',
    'feedback.thanks': 'Thank you! Complaint closed.',
    'feedback.thanksSub': 'धन्यवाद! शिकायत बंद हुई।',
    'feedback.reopened': 'Complaint reopened',
    'feedback.reopenedSub': 'Reopened and sent back. We will update you.',
    'voice.title': 'Speak your complaint',
    'voice.titleSub': 'बोलकर शिकायत करें',
    'voice.instruction': 'Press the red button and start speaking',
    'voice.instructionSub': 'लाल बटन दबाएँ और बोलना शुरू करें',
    'voice.tapToRecord': 'Tap to record · बटन दबाएँ',
    'voice.recording': 'Recording… · सुन रहे हैं…',
    'voice.recorded': 'Recorded · रिकॉर्ड हो गया',
    'voice.rerecord': 'Re-record · दोबारा बोलें',
    'voice.next': 'Next · आगे',
    'loc.detected': 'detected',
    'loc.orSelect': 'Or select from below · या नीचे से जगह चुनें',
    'loc.error': 'GPS not found',
    'loc.errorSub': 'Location access denied or unavailable',
    'loc.retry': 'Retry',
    'other.placeholder': 'Describe your problem here…',
    'other.placeholderEn': 'अपनी समस्या यहाँ लिखें…',
    'login.title': 'Login',
    'login.titleSub': 'लॉगिन करें',
    'login.name': 'Your name · आपका नाम',
    'login.namePlaceholder': 'Enter your name',
    'login.phone': 'Mobile number · मोबाइल नंबर',
    'login.sendOtp': 'Send OTP · OTP भेजें',
    'login.otp': 'Enter OTP · OTP डालें',
    'login.otpSent': 'OTP sent to · OTP भेजा गया',
    'login.verify': 'Verify · पुष्टि करें',
    'login.changePhone': 'Change number · नंबर बदलें',
    'login.phoneError': 'Please enter a 10-digit number',
    'login.nameError': 'Please enter your name',
    'login.otpError': 'Wrong OTP · Demo OTP: 1234',
    'login.demo': 'Demo: Use any 10-digit number and OTP 1234 to login',
    'login.logout': 'Logout · लॉगआउट',
    'voice.transcribing': 'Transcribing… · समझ रहे हैं…',
    'voice.transcript': 'You said · आपने कहा',
    'voice.detected': 'Department detected · विभाग पहचाना',
    'map.title': 'Choose on map',
    'map.titleSub': 'नक्शे पर जगह चुनें',
    'map.search': 'Search location',
    'map.select': 'Select this location',
    'track.noComplaints': 'No complaints yet',
    'track.noComplaintsSub': 'अभी कोई शिकायत नहीं है। होम से नई शिकायत करें।',
    'track.fileNew': 'File new complaint · नई शिकायत करें',
  },
};

interface LangContextType {
  language: Lang;
  setLanguage: (lang: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  language: 'hi',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Lang>('hi');

  const t = useCallback(
    (key: string): string => translations[language][key] ?? key,
    [language]
  );

  return (
    <LangContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
